#!/usr/bin/env sh

export VERSION="$1"
export WINEPREFIX="$2"
export DOWNLOADS="${HOME}/Downloads"
export ZIPFILE="dxvk-${VERSION}.tar.gz"
export URL="https://github.com/doitsujin/dxvk/releases/download/v${VERSION}/${ZIPFILE}"

if [ ! -e "${DOWNLOADS}/${ZIPFILE}" ]; then
    wget "$URL" -P "$DOWNLOADS"
fi
tar xf "${DOWNLOADS}/$ZIPFILE" -C "$DOWNLOADS"

"$DOWNLOADS/dxvk-${VERSION}/setup_dxvk.sh" install

# create dxvk structure in wineprefix
export DXVKDIR=${WINEPREFIX}/drive_c/dxvk
mkdir -p "${DXVKDIR}/cache" \
    "${DXVKDIR}/log"
echo 'd3d11.maxTessFactor = 8' > "${DXVKDIR}/dxvk.conf"
