#!/bin/sh

if [ $# -lt 2 ]
then
	echo "usage: $0 <target dir> <cdrom dir>" >&2
	exit 1
fi

BASE=$1/base
MEGATEXTURES=$BASE/megatextures

if [ ! -d $BASE ]
then
	mkdir -p $BASE
fi

if [ ! -d $MEGATEXTURES ]
then
	mkdir -p $MEGATEXTURES
fi

install -o $USER -t $BASE $2/setup/data/base/pak*
install -o $USER -t $BASE $2/setup/data/base/zpak_*
install -o $USER -t $MEGATEXTURES $2/setup/data/base/megatextures/*.mega
