#!/bin/bash

CONFFILE=$HOME/.porndown

cleanup() {
	# clean up the working files
	if [ -n "$TMPFILE" ]
	then
		rm $TMPFILE
	fi
	if [ -n "$DESTINATIONFILE" ]
	then
		rm $DESTINATIONFILE
	fi

	echo ""
	echo "-- interrupted -> cleaning up --"
	exit 0
}

doElement() {
	ELEMENT=$1

	if [ -r $ELEMENT ]
	then
		doFile $ELEMENT
	else
		doLink $ELEMENT
	fi
}

doFile() {
	LINKFILE=$1

	# read the file linewise
	while read LINE
	do
		doElement $LINE

		# remove the entry from the file if wanted
		if [ "$CLEAN_LINKFILES" == "1" ]
		then
			sed -e '1d' -i $LINKFILE
		fi
	done < $LINKFILE

	# delete the file if wanted
	if [ "$REMOVE_LINKFILES" == "1" ]
	then
		rm $LINKFILE
	fi
}

doLink() {
	TMPFILE=$(mktemp)

	# get the html file containing the information
	wget -q -O $TMPFILE $1

	# get title from the html file
	TITLE=$(sed -n -e 's|<title>\(.*\)</title>|\1|p' $TMPFILE)
	# clean the title from not valid characters
	TITLE=$(echo $TITLE | sed -e 's|[^a-zA-Z0-9 _-]||g')
	# video url from the html file
	URL=$(sed -n -e 's|var videourl="\([a-zA-Z0-9/.:_-]*\)";|\1|p' $TMPFILE)

	# compute the output filename
	FILENAME=$(echo $TITLE | sed -e 's|\(.*\) - \(.*\) - \(.*\)|\1|' \
		-e 's| |_|g')

	DESTINATIONFILE=${DESTDIR}${FILENAME}.${URL##*.}

	# while the destination file already exists add a incrementing number to the filename
	COUNTER=1
	while [ -f $DESTINATIONFILE ]
	do
		DESTINATIONFILE=${DESTDIR}${FILENAME}_$((COUNTER++)).${URL##*.}
	done

	# create the output directory
	if [ ! -d $DESTDIR ]
	then
		mkdir -p $DESTDIR
	fi

	# download the file
	echo Downloading: $DESTINATIONFILE
	wget -q -O $DESTINATIONFILE $URL

	rm $TMPFILE
}

trap "cleanup" HUP #SIGHUP SIGINT SIGQUIT SIGTERM

# no args given
if [ $# -lt 1 ]
then
	echo "usage: $0 <url|file> ..." >&2
	exit
fi

# load the config file
if [ -r $CONFFILE ]
then
	. $CONFFILE
	DESTDIR=$DIR/
else
	DESTDIR=./
fi

# download the videos
for arg in $@
do
	doElement $arg
done

echo "-- done --"
