#!/bin/sh

VIMVER="7.1"

if [ $# -lt 2 ] ; then 
	echo "usage is: $0 <from> <to> [vim version]";
	exit;
fi;
if [ $# -ge 3 ] ; then
	VIMVER=$3;
fi;
	
curl ftp://ftp.vim.org/pub/vim/patches/$VIMVER/$VIMVER.[$1-$2] -o "$VIMVER.#1"
